services:
  postgres:
    image: postgres:16-alpine
    container_name: finance-analytics-postgres
    environment:
      POSTGRES_DB: finance_analytics
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_password
    ports:
      - "5432:5432"
    volumes:
      - finance_pgdata:/var/lib/postgresql/data

volumes:
  finance_pgdata:
